### ISSUE TITLE
git_ops.message_hook fails

### ISSUE THREAD

**Issue by heywhy** [zachdaniel/git_ops#54]
Tried installing the message hook for convention checks but it fails with the below:

```
** (KeyError) key :error not found in: %Git.Error{args: ["core.hookspath"], code: 1, command: "config", message: ""}
    lib/git_ops/git.ex:90: GitOps.Git.handle_hooks_path_error/1
    lib/mix/tasks/git_ops.message_hook.ex:180: Mix.Tasks.GitOps.MessageHook.commit_msg_hook_info!/1
    lib/mix/tasks/git_ops.message_hook.ex:61: Mix.Tasks.GitOps.MessageHook.install/1
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by zachdaniel** [comment]
fixed in #55
