### ISSUE TITLE
"No changes " error after commit

### ISSUE THREAD

**Issue by marinakr** [zachdaniel/git_ops#8]
In my umbrella project  after `mix git_ops.release --initial` I get error: 
```
** (ArgumentError) cannot use an empty string as the match to replace
    (elixir) lib/string.ex:823: String.replace_leading/3
    lib/mix/tasks/git_ops.release.ex:100: Mix.Tasks.GitOps.Release.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```
and after commit commit like "fix: certificates updated"
I get error  when I do mix git_ops.release in docker container:
```
/home/ds# MIX_ENV=dev mix git_ops.release
** (RuntimeError) No changes should result in a new release version.

Options:

* If no fixes or features were added, then perhaps you don't need to release.
* If a fix or feature commit was not correctly annotated, you could alter your git
  history to fix it and run this command again, or create an empty commit via
  `git commit --allow-empty` that contains an appropriate message.
* If you don't care and want a new version, you can use `--force-patch` which
  will update the patch version regardless.
* You can add build metadata using `--build` that will signify that something was
  unique about this build.

    lib/git_ops/version.ex:25: GitOps.Version.determine_new_version/4
    lib/mix/tasks/git_ops.release.ex:92: Mix.Tasks.GitOps.Release.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2"
```
My mix.exs:
 ```
 defp deps do
    [
      {:git_ops, "~> 0.5.0", only: [:dev]},
      {:distillery, "~> 2.0", runtime: false, override: true},
      {:credo, "~> 0.9.3", only: [:dev, :test]},
      {:excoveralls, "~> 0.8.1", only: [:dev, :test]}
    ]
  end
```
and config:
```
config :git_ops,
  mix_project: DigitalSignatureUmbrella.MixProject,
  changelog_file: "CHANGELOG.md",
  repository_url: "https://github.com/edenlabllc/ds.api/",
  types: [
    # Makes an allowed commit type called `tidbit` that is not
    # shown in the changelog
    tidbit: [
      hidden?: true
    ],
    # Makes an allowed commit type called `important` that gets
    # a section in the changelog with the header "Important Changes"
    important: [
      header: "Important Changes"
    ]
  ],
  # Instructs the tool to manage your mix version in your `mix.exs` file
  # See below for more information
  manage_mix_version?: true,
  # Instructs the tool to manage the version in your README.md
  # Pass in `true` to use `"README.md"` or a string to customize
  manage_readme_version: "README.md"
```

My commit:
`git commit -am "fix: Update sign + stamp content"`

This project use `.so` files so in OSX it can be compiled only in docker container
Out of docker I get same error

**Comment by marinakr** [comment]
Same error occurs when git_ops it to one of apps

**Comment by marinakr** [comment]
Updated error
https://github.com/edenlabllc/ds.api/pull/31 - PR where this lib added

**Comment by marinakr** [comment]
First error` mix git_ops.release --initial`  was fixed by adding `version_tag_prefix: "v"` into config.exs:
```
config :git_ops,
  version_tag_prefix: "v",
  mix_project: DigitalSignatureUmbrella.MixProject,
  changelog_file: "CHANGELOG.md",
  ...
```

**Comment by marinakr** [comment]
After debugging I see the problem in function `GitOps.Version.last_valid_non_rc_version(versions, prefix)`  when version_tag_prefix in config set to "v"
`Git.log!(["#{tag}..HEAD", "--format=%B--gitops--"])`, it do not returned tag and no commits returned returned in function `GitOps.Git.commit_messages_since_tag`. But if I set version_tag_prefix to "", I get error: 
```
MIX_ENV=dev mix git_ops.release 
Commit with unknown type: style: add comment for version_tag_prefix
** (ArgumentError) cannot use an empty string as the match to replace
    (elixir) lib/string.ex:823: String.replace_leading/3
```

**Comment by zachdaniel** [comment]
Hello @marinakr. Sorry you are having issues with `git_ops`. I don't have time today, unfortunately, to look into this but I will look into it and hopefully resolve it first thing in the morning tomorrow (I'm in EST). If you find a fix, feel free to PR it and I will review it as soon as possible. Otherwise, I'll let you know what I find tomorrow morning!

**Comment by zachdaniel** [comment]
It looks like this may also be resolved via your PR, correct? Now that you can use the correct prefix?

**Comment by marinakr** [comment]
fixed
